# theme                  : "minimal-mistakes-jekyll"
remote_theme             : "iovcc/minimal-mistakes@iovcc_theme"
minimal_mistakes_skin    : "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

title: IO/VCC
description: "An International Obfuscated *HDL Code Contest (Why Verilog? For the name to be good: IOVCC)"
tags: HDL, VHDL, Verilog, Bluespec, SystemVerilog, chisel, iverilog, verelator, multsim, xilinx, intel, Risc-V, Altera, Ciclone, NLCP

locale: pt-BR
timezone: America/Sao_Paulo

permalink: /posts/:categories/:title/

paginate: 6 # amount of posts to show
paginate_path: /posts/page:num/

repository               : iovcc/iovcc.github.io 
teaser                   : /assets/images/banner_2.png # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : /assets/images/icon.png# path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs            : true # true, false (default)

comments:
  provider               : staticman # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  staticman:
    branch               : master # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single    

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

include: ["_pages"]
exclude: [LICENSE, README.md, Gemfile, .gitignore, Gemfile.lock]