# theme                  : "minimal-mistakes-jekyll"
remote_theme             : "iovcc/minimal-mistakes@iovcc_theme"
minimal_mistakes_skin    : "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

title: IO/VCC
description: "An International Obfuscated *HDL Code Contest (Why Verilog? For the name to be good: IOVCC)"
tags: HDL, VHDL, Verilog, Bluespec, SystemVerilog, chisel, iverilog, verelator, multsim, xilinx, intel, Risc-V, Altera, Ciclone, NLCP

locale: pt-BR
timezone: America/Sao_Paulo

paginate: 6 # amount of posts to show
paginate_path: /posts/page:num/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single    

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

include: ["_pages"]
exclude: [LICENSE, README.md, Gemfile, .gitignore, Gemfile.lock]